---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD007:
  start_indented: true        # Unordered lists are fully indented
MD013:
  line_length: 200            # Line length 80 is far to short

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
